version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URI:mongodb+srv://v2dent:Chelsea24462!@v2dentdb.pijmi.mongodb.net/v2dent?retryWrites=true&w=majority
    command: npm run start